version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/html/
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www/html/
    owner: apache
    group: apache  
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
