version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      runas: root
