version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies required"
  build:
    commands:
      - echo "Build phase started"
      - ls -al
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - index.html
    - style.css
    - appspec.yml
    - scripts/**/*
  discard-paths: no
