version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies required for static website"
  build:
    commands:
      - echo "Build phase - copying files"
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  discard-paths: no
